### ISSUE TITLE
New border have 2 problem since 2.0.0 version

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Border#37]
https://streamable.com/3kdrgn

**Comment by BONNe** [comment]
:D well :D there is a border :D

Just avoid flying over and under it :D

It is like a border wall... XD

Tasty, I would say you should just cancel movement and do not even bother with barrier blocks.

**Comment by tastybento** [comment]
It's not designed to be impossible to cross. It's just meant to show where the island edge is.

I have done a lot of these in the past, and the canceling movement has problems too, especially if you end up on the other side of the wall due to speed or vehicle movement. It ends up requiring a lot of sophisticated code, similar to the island lock. I'll look into it, but if you need an indestructible border, use the older version for now.

**Comment by OverBrave** [comment]
Have you watched the end of the video? Because now there is a bug that needs to be fixed.

**Comment by tastybento** [comment]
I can't tell what it is. Can you describe in words?

**Comment by OverBrave** [comment]
When close border with command "/is border off", barriers continue to remain there.
Watch in 1:20

**Comment by tastybento** [comment]
Okay, try 2.0.1 snapshot when it builds and let me know if that works for you.

**Comment by SlimeCody** [comment]
Please either make it configurable or another add-on for the 2 border types.

**Comment by tastybento** [comment]
@SlimeCody I don't understand. Make what configurable?

**Comment by Ac3dUd3** [comment]
barriers are a bad idea anyway IMO. my players can sneak click their way through it onto other islands.

I reverted back to the old barrier

**Comment by SlimeCody** [comment]
Make it configurable to where we can hook into the worldborder api, or use the barrier one.
